package jm.task.core.jdbc.service;

import jm.task.core.jdbc.model.User;
import jm.task.core.jdbc.util.Util;

import java.sql.*;
import java.util.LinkedList;
import java.util.List;

public class UserServiceImpl implements UserService {
    private Util conn = new Util();
    public void createUsersTable() {
        try(Connection connect = conn.connection()){
            Statement statement = connect.createStatement();
            statement.executeUpdate(
                    "CREATE TABLE IF NOT EXISTS users (" +
                            "id INTEGER  GENERATED BY DEFAULT AS IDENTITY," +
                            "firstName VARCHAR(255)," +
                            "lastName VARCHAR(255)," +
                            "age SMALLINT)");
        } catch (SQLException | ClassNotFoundException e) {
            System.out.println("Что-то не так при подключении к БД " + e);
        }
    }

    public void dropUsersTable() {
        try(Connection connect = conn.connection()){
            Statement statement = connect.createStatement();
            statement.executeUpdate("DROP TABLE IF EXISTS users");
        } catch (SQLException | ClassNotFoundException e) {
            System.out.println("Что-то не так при подключении к БД! " + e);
        }
    }

    public void saveUser(String name, String lastName, byte age) {
        try(Connection connect = conn.connection()){
            PreparedStatement statement = connect.prepareStatement("INSERT INTO users ( firstName," +
                    "lastName, age) VALUES (?,?,?)");
            statement.setString(1, name);
            statement.setString(2, lastName);
            statement.setByte(3, age);
            statement.executeUpdate();
            System.out.printf("User с именем - %s добавлен в базу данных \n", name);
        } catch (SQLException | ClassNotFoundException e) {
            System.out.println("Что-то не так при подключении к БД!! " + e);
        }
    }

    public void removeUserById(long id) {
        try(Connection connect = conn.connection()){
            PreparedStatement statement = connect.prepareStatement("DELETE FROM users WHERE id =?");
            statement.setLong(1, id);
            statement.executeUpdate();
        } catch (SQLException | ClassNotFoundException e) {
            System.out.println("Что-то не так при подключении к БД!!! " + e);
        }
    }

    public List<User> getAllUsers() {
        List<User> list = new LinkedList<>();
        try (Connection connect = conn.connection();
             PreparedStatement pst = connect.prepareStatement("SELECT id, firstName, lastName, age FROM users ORDER BY id");
             ResultSet rs = pst.executeQuery()) {
            while (rs.next()) {
                User user = new User();
                user.setId(rs.getLong("id"));
                user.setName(rs.getString("firstName"));
                user.setLastName(rs.getString("lastName"));
                user.setAge(rs.getByte("age"));
                list.add(user);
            }
        } catch (SQLException | ClassNotFoundException e) {
            System.out.println("Что-то не так при подключении к БД!- " + e);
        }
        return list;
    }

    public void cleanUsersTable() {
        try(Connection connect = conn.connection()){
            Statement statement = connect.createStatement();
            statement.executeUpdate("TRUNCATE users RESTART IDENTITY ");
        } catch (SQLException | ClassNotFoundException e) {
            System.out.println("Что-то не так при подключении к БД!+ " + e);
        }
    }
}
