package jm.task.core.jdbc.dao;

import jm.task.core.jdbc.model.User;
import jm.task.core.jdbc.util.Util;
import org.hibernate.Session;
import org.hibernate.jdbc.Work;


import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

public class UserDaoHibernateImpl implements UserDao {
   private Util connect = new Util();

    public UserDaoHibernateImpl() {}

    @Override
    public void createUsersTable() {
        try (Session session = Util.getSessionFactory().openSession()) {
            session.doWork(new Work () {
                @Override
                public void execute(Connection connection) throws SQLException {
                   Statement statement = connection.createStatement();
                   statement.executeUpdate("CREATE TABLE IF NOT EXISTS users (" +
                           "id INTEGER  GENERATED BY DEFAULT AS IDENTITY," +
                           "firstName VARCHAR(255)," +
                           "lastName VARCHAR(255)," +
                           "age SMALLINT)");
                   connection.commit();
                   connection.close();
                }
            });

        } catch (Exception e) {
            System.out.println("Что-то не так при подключении к БД! " + e);
        }
    }

    @Override
    public void dropUsersTable() {
        try (Session session = Util.getSessionFactory().openSession()) {
            session.doWork(new Work () {
                @Override
                public void execute(Connection connection) throws SQLException {
                    Statement statement = connection.createStatement();
                    statement.executeUpdate("DROP TABLE IF EXISTS users");
                    connection.commit();
                    connection.close();
                }
            });
        } catch (Exception e) {
            System.out.println("Что-то не так при подключении к БД! " + e);
        }
    }

    @Override
    public void saveUser(String name, String lastName, byte age) {
        Session session = Util.getSessionFactory().openSession();
        session.beginTransaction();
        User user = new User();
        user.setName(name);
        user.setLastName(lastName);
        user.setAge(age);
        session.persist(user);
        session.getTransaction().commit();
        session.close();
    }

    @Override
    public void removeUserById(long id) {

    }

    @Override
    public List<User> getAllUsers() {
        return null;
    }

    @Override
    public void cleanUsersTable() {

    }
}
