package jm.task.core.jdbc.dao;

import jm.task.core.jdbc.model.User;
import java.util.List;
import jm.task.core.jdbc.util.Util;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import java.sql.*;
import java.util.LinkedList;

public class UserDaoHibernateImpl implements UserDao {
    private Util connect = new Util();

    public UserDaoHibernateImpl() {}

    @Override
    public void createUsersTable() {
        Session session = connect.hibConnect().openSession();
        try {
            Transaction transaction = session.beginTransaction();
            String sql = "CREATE TABLE IF NOT EXISTS users (" +
                     "id INTEGER  GENERATED BY DEFAULT AS IDENTITY," +
                     "firstName VARCHAR(255)," +
                     "lastName VARCHAR(255)," +
                     "age SMALLINT)";
            session.createQuery(sql);
            transaction.commit();
            session.close();

        } catch (Exception ex){
            System.out.println("Что-то не так при подключении к БД! " + ex);
        }
    }

    @Override
    public void dropUsersTable() {

    }

    @Override
    public void saveUser(String name, String lastName, byte age) {

    }

    @Override
    public void removeUserById(long id) {

    }

    @Override
    public List<User> getAllUsers() {
        return null;
    }

    @Override
    public void cleanUsersTable() {

    }
}
